services:
  ssh-jumphost:
    build:
      context: .
      dockerfile: ssh-jumphost/Dockerfile
    configs:
      - source: authorized_keys
        target: /run/secrets/authorized_keys
      - source: keyfetch_key
        target: /run/secrets/keyfetch_key
      - source: keyfetch_key_pub
        target: /run/secrets/keyfetch_key.pub
      - source: ssh_key_repo
        target: /run/secrets/ssh_key_repo
    environment:
      - DEBUG
    ports:
      - "${SSH_PORT:-2223}:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssh-jumphost/etc/ssh/sshd_config.d/00-custom.conf:/etc/ssh/sshd_config.d/00-custom.conf:ro
      - ./ssh-jumphost/usr/local/sbin/authorized-keys-lookup:/usr/local/sbin/authorized-keys-lookup:ro
      - ./ssh-jumphost/usr/local/sbin/router.sh:/usr/local/sbin/router:ro
    restart: unless-stopped
    networks:
      - dokploy-network
      - default

configs:
  authorized_keys:
    file: /root/.ssh/authorized_keys
  keyfetch_key:
    file: /root/.ssh/keyfetch_key
  keyfetch_key_pub:
    file: /root/.ssh/keyfetch_key.pub
  ssh_key_repo:
    content: |
      ${SSH_KEY_REPO:-git@github.com:nathaneyre/ssh-authorized-keys.git}

networks:
  dokploy-network:
    external: true