AuthorizedKeysCommand /bin/sh /usr/local/sbin/authorized-keys-lookup
AuthorizedKeysCommandUser keyfetch

AllowUsers root
PermitRootLogin prohibit-password
PasswordAuthentication no
ForceCommand /bin/sh /usr/local/sbin/router

AllowAgentForwarding yes
AllowTcpForwarding yes
PermitTTY yes
PermitUserEnvironment yes