AuthorizedKeysCommand /bin/sh /usr/local/sbin/authorized-keys-lookup
AuthorizedKeysCommandUser keyfetch
ForceCommand /bin/sh /usr/local/sbin/router
PermitTTY yes
AllowTcpForwarding yes
PermitUserEnvironment yes
AllowUsers root
PasswordAuthentication no